svelte update to 5.38.5
improved error message from:

  TypeError: Cannot read properties of null (reading 'fn')

to:

  Updating state inside `$derived(...)`, `$inspect(...)` or a template expression is forbidden.
  If the value should not be reactive, declare it without `$state`
  https://svelte.dev/e/state_unsafe_mutation